name: Publish Node.js Package

on:
  release:
    types: [created]

permissions:
  contents: read        # To access repository contents
  packages: write       # To publish the package
  id-token: write       # For GitHub OIDC auth

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: https://registry.npmjs.org/

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          echo "@${{ github.repository_owner }}:registry=https://registry.npmjs.org/" >> ~/.npmrc
          npm publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

      - name: Debug .npmrc and registry
        run: |
          echo "--- .npmrc ---"
          cat ~/.npmrc
          echo "--- npm registry ---"
          npm config get registry

      - name: Clear .npmrc before setting up for GitHub Packages
        run: rm -f ~/.npmrc

      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          npm config get registry  # Verify that registry is correct
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
