name: Publish Node.js Package

on:
    release:
        types: [created]

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    publish-npm-package:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: https://registry.npmjs.org/
                  cache: "yarn" # cache Yarn downloads; faster installs

            # 👇 Make sure Yarn v4 from package.json > packageManager is used
            - name: Enable Corepack & activate Yarn
              run: |
                  corepack enable
                  corepack prepare yarn@4.10.3 --activate
                  yarn --version

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run tests
              run: yarn test

            - name: Build project
              if: ${{ success() }}
              run: yarn build

            - name: Configure npm auth
              run: |
                  echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
                  npm whoami
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

            - name: Publish to npm
              if: ${{ success() }}
              run: npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
