name: Publish Node.js Package

on:
  release:
    types: [created]

permissions:
  contents: read        # To access repository contents
  packages: write       # To publish the package
  id-token: write       # For GitHub OIDC auth

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: https://registry.npmjs.org/

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build project
        if: ${{ success() }}
        run: yarn build

      # Publish to npm
      - name: Publish to npm
        if: ${{ success() }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          echo "@${{ github.repository_owner }}:registry=https://registry.npmjs.org/" >> ~/.npmrc
          npm publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

